config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
 end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  post "/given_answers/new" , to: "given_answers#create" 
  root "quizzes#index"

  resources :questions
  resources :quizzes
  resources :given_answers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/given_answer.rb
class GivenAnswer < ApplicationRecord
  belongs_to :question
  belongs_to :user
  belongs_to :quiz

  
end

app/models/option.rb
class Option < ApplicationRecord
  belongs_to :question
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :options
  has_many :given_answers
  belongs_to :quiz
end

app/models/quiz.rb
class Quiz < ApplicationRecord
    has_many :questions
    has_many :given_answers

    

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :quizzes 
         has_many :given_answers

         def is_admin?
          self.name == 'admin'
        end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end
end

app/controllers/given_answers_controller.rb
class GivenAnswersController < ApplicationController

    def index
        @given = GivenAnswer.all
        @answers = current_user.given_answers
    end
    
    def new 
        @given = GivenAnswer.new
    end
    

    def create
        @given = GivenAnswer.new(given_params)
        if @given.save
            
        else
            render :new, status: :unprocessable_entity
            flash[:message] = "Try Again"
        end
    end

    def given_params
        params.permit(:question_id, :user_id, :quiz_id, :given_option_number)
    end


end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
    
    def index
        @questions =  Question.all 
    end
    
    
    def new
        @question = Question.new
    end
    
    def create
        @question = Question.new(question_params)
        
        if @question.save
            redirect_to @question
        else
            render :new, status: :unprocessable_entity
            flash[:message] = "Try Again"
        end
    end

    def question_params
        params.require(:question).permit( :question_number, :question_content, :correct_answer, :option_content_one, 
        :option_content_two, :option_content_three, :option_content_four, :quiz_id )
    end

end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
    before_action :authenticate_user!
    def index
        @quizzes = Quiz.all
    end

    def show
        @quiz=  Quiz.find(params[:id])
    end





    def create
        @given = GivenAnswer.new(given_params)
        if @given.save
            redirect_to @question
        else
            render :new, status: :unprocessable_entity
            flash[:message] = "Try Again"
        end
    end

    def given_params
        params.require(:question).permit(:given_option_number, :user_id, :question_id)
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/given_answers/index.html.erb
 <% Quiz.all.each do |quiz| %>
   <h1> <%= quiz.quiz_category %> category </h1>
    <table class="table w-100">
        <tr>
            <th>Question</th>
            <th>Correct Answer</th>
            <th>Your Answer</th>
            <th>Result</th>
        </tr>
        <% @answers.where(quiz_id: quiz.id).last(3).each do |ga| %>
            <tr>
                <td> <%= Question.find(ga.question_id).question_content %> </td>
                <td> <%= Question.find(ga.question_id).correct_answer %> </td>
                <td> <%= ga.given_option_number %> </td>
               

            <% if ga.given_option_number == Question.find(ga.question_id).correct_answer %>
                <td> correct </td>
             <% else %>
                 <td> wrong </td>
             <% end %>

            </tr>
        <%end%>

    </table>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quizapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  </head>

  <body>
  <nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href=" <%= root_path %> ">
    <img src="https://img.freepik.com/premium-vector/quiz-logo-poll-questionnaire-icon-symbol_101884-1076.jpg" width="45" height="45" class="d-inline-block align-top navicon" alt="">
    <span class="navtext">Quizziee</span>
  </a>

  <% if current_user %>
  <%= link_to "log out" , destroy_user_session_path, method: :delete, class: "btn btn-danger",style:"margin-right:10px" %>
  <% end %>
</nav>
    <%= yield %>
  </body>
</html>

app/views/questions/new.html.erb
<%= form_with model: @question do |form| %>
    <div>
      <%= form.label :question_number %><br>
      <%= form.text_field :question_number %>
    </div>
  
    <div>
      <%= form.label :question_content %><br>
      <%= form.text_area :question_content %>
    </div>

    <div>
      <%= form.label :correct_answer %><br>
      <%= form.text_area :correct_answer %>
    </div>

    <div>
    <%= form.label :option_content_one %><br>
    <%= form.text_area :option_content_one %>
    </div>

    <div>
    <%= form.label :option_content_two %><br>
    <%= form.text_area :option_content_two %>
    </div>

    <div>
    <%= form.label :option_content_three %><br>
    <%= form.text_area :option_content_three %>
    </div>

    <div>
    <%= form.label :option_content_four %><br>
    <%= form.text_area :option_content_four %>
    </div>

    <div class="field">
        <%=form.label:quiz_id%><br />
        <%=form.select:quiz_id,Quiz.all.collect{|quiz| [quiz.quiz_category,quiz.id]}%>
    </div>
  
    <div>
      <%= form.submit %>
    </div>
<% end %>

app/views/quizzes/index.html.erb
<h1> CATEGORIES </h1>

<% @quizzes.each do |q| %>
    <div class="">
    <%= button_to q.quiz_category , quiz_path(q) , method: :get , class:"cat-box"%>
    </div>
<% end %>

<% if current_user.is_admin? %>
<%= button_to "Add Question", new_question_path ,method: :get, class:"btn btn-primary "%> 
<%end%>

app/views/quizzes/show.html.erb
<% Question.where(quiz_id:@quiz.id).each do |q| %>

    <div>
    <%= q.question_number %>
    <%= q.question_content %></br>
    <%= q.option_content_one %>
    <%= q.option_content_two %>
    <%= q.option_content_three %>
    <%= q.option_content_four %>

  
    <%= form_with url: "/given_answers/new", method: :post do |form| %>

        <div class="form-group">
            <%= form.radio_button :given_option_number, "A" %>
            <%= form.label :given_option_number, "A" %>

            <%= form.radio_button :given_option_number, "B" %>
            <%= form.label :given_option_number, "B" %>

            <%= form.radio_button :given_option_number, "C" %>
            <%= form.label :given_option_number, "C" %>

            <%= form.radio_button :given_option_number, "D" %>
            <%= form.label :given_option_number, "D" %>
        </div>

        <div>
        <%= form.hidden_field :question_id, value: q.id %>
        </div>

        <div>
        <%= form.hidden_field :user_id, value: current_user.id %>
        </div>

        <div>
        <%= form.hidden_field :quiz_id, value: @quiz.id %>
        </div>

        <div>
        <%= form.submit "Submit" %>
        </div>


    <% end %>

<% end %>

<%= button_to "View Results" , given_answers_path , method: :get %>